port: 7880
log_level: info

rtc:
  tcp_port: 7881
  udp_port: 7882
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

redis:
  address: redis:6379

turn:
  enabled: true
  domain: turn.wikylyu.xyz
  tls_port: 5349
  external_tls: true

keys:
  APIgPS83rYg5STf: dxEidipndJfx0RTlGXVb6S6XcV3wLUFgVGO6nM9x4aU
